arch:
  - amd64
  - ppc64le
dist: xenial
language: python
cache: pip
services:
  - postgresql
python:
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - sudo chown -Rvf $USER:$GROUP ~/.cache/pip/wheels
install:
  - pip install -r requirements-py3.txt
  - pip install coveralls
before_script:
  - psql -U postgres -c 'CREATE DATABASE dummy_test'
script:
  - nosetests --with-coverage --cover-package=csvkit
after_success:
  coveralls
